version: '2.0'
services:
  web:
    build: .
    command: bash -c "python app/db.py && python app/main.py"
    ports:
    - "8080:8080"
    networks:
      - net
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://postgres@db:5432/postgres
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
